import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { createAppHarness } from './helpers/app-harness.mjs';

test('lógica: auditoría de los 50 ejercicios y paneles', async () => {
  const harness = await createAppHarness();
  const { getElementById } = harness;
  const actions = harness.actions;
  const html = await readFile(new URL('../index.html', import.meta.url), 'utf8');
  const logicCovered=new Set();
  const logicDefaults={bases:{mode:'convert',a:'156',b:'0',from:10,to:2,width:8,op:'add'},sets:{mode:'sets',a:'1,2,3,4',b:'4,5',pairs:'1,1',n:4,m:4,outer:'forall',inner:'exists','infinite-domain':'Z',sizes:'30,25',intersections:'10',triple:0,universe:'60',predicate:'x^2<10',slope:2,intercept:1,power:2},propositions:{mode:'table',expression:'p∧¬q',premises:'p→q',conclusion:'q',induction:'squares',n:10},boolean:{mode:'minimal',source:'minterms',expression:'(A∨B)∧(¬A∨C)',names:'A,B,C',minterms:'1,3,5,6,7',dontcare:''},graphs:{mode:'summary',edges:'A B\nA C\nB C\nC D\nD E',start:'A',target:'E',directed:'undirected',sequence:'4,3,3,2,2',tree:'{}','count-edges':7,'count-vertices':6,'count-left':3,'count-right':4,'count-leaves':8}};
  const logicPrefix={bases:'base',sets:'set',propositions:'prop',boolean:'bool',graphs:'graph'};
  const logicAction={bases:'logicCalculateBases',sets:'logicCalculateSets',propositions:'logicCalculateProposition',boolean:'logicCalculateBoolean',graphs:'logicCalculateGraph'};
  function logicCase(id,panel,fields,patterns){
    actions.logicOpenPanel(panel);const markup=getElementById('logic-content').innerHTML;
    assert.match(markup,new RegExp(`data-action="${logicAction[panel]}"`));
    for(const [key,value] of Object.entries({...logicDefaults[panel],...fields})){const control=`logic-${logicPrefix[panel]}-${key}`;assert.ok(markup.includes(`id="${control}"`),`Lógica ${id}: ${control}`);getElementById(control).value=String(value);}
    actions[logicAction[panel]]();assert.equal(getElementById('logic-result').classList.contains('tool-error'),false,`Lógica ${id}: ${getElementById('logic-result').textContent}`);
    const html=getElementById('logic-result').innerHTML;for(const pattern of patterns)assert.match(html,pattern,`Lógica ${id}`);logicCovered.add(id);
  }
  const lb=(id,fields,patterns)=>logicCase(id,'bases',fields,patterns);
  const ls=(id,fields,patterns)=>logicCase(id,'sets',fields,patterns);
  const lp=(id,fields,patterns)=>logicCase(id,'propositions',fields,patterns);
  const lk=(id,fields,patterns)=>logicCase(id,'boolean',fields,patterns);
  const lg=(id,fields,patterns)=>logicCase(id,'graphs',fields,patterns);
  lb(1,{},[/10011100/]);lb(2,{a:'10110101',from:2,to:10},[/181/]);lb(3,{a:'A3F',from:16,to:10},[/2623/]);lb(4,{a:'725',from:8,to:2},[/111010101/]);
  lb(5,{mode:'arithmetic',a:'1101',b:'1011',from:2,op:'add'},[/11000/]);lb(6,{mode:'arithmetic',a:'1010',b:'101',from:2,op:'multiply'},[/110010/]);
  ls(7,{a:'1,2,3,4,5',b:'4,5,6,7'},[/1, 2, 3, 4, 5, 6, 7/,/4, 5/,/1, 2, 3, 6, 7/]);
  ls(8,{mode:'count',n:6,m:0},[/subconjuntos de A = 64/]);ls(8,{mode:'count',n:4,m:5},[/\|A×B\| = 20/]);
  lp(9,{expression:'p∧¬q'},[/4 asignaciones/,/<th>p<\/th><th>q<\/th>/]);lp(10,{expression:'(p→q)↔(¬p∨q)'},[/tautology/]);
  lp(11,{mode:'negations'},[/¬\(p∧q\) ⇔ ¬p∨¬q/,/∃x\(x≤2\)/,/doble negación/]);
  ls(12,{mode:'predicate',a:'1,2,3,4',predicate:'x^2<10'},[/∀x P\(x\): falso/,/∃x P\(x\): verdadero/,/contraejemplo: 4/]);
  lk(13,{source:'formula',names:'A,B',expression:'A∧(A∨B)'},[/F = A\./]);lp(14,{expression:'A∧B∨¬A'},[/4 asignaciones/,/contingent/]);
  lg(15,{mode:'counts'},[/2E<\/td><td>14/,/n\(n−1\)\/2<\/td><td>15/]);lg(16,{mode:'counts','count-vertices':15,'count-leaves':8},[/n−1<\/td><td>14/,/2L−1<\/td><td>15/]);
  ls(17,{mode:'relation',a:'1,2,3',pairs:'1,1\n1,2\n2,3'},[/Dominio observado = \{1, 2\}/,/rango = \{1, 2, 3\}/,/Contraejemplo/]);
  lb(18,{a:'0.6875',from:10,to:2},[/0\.1011/]);lb(18,{a:'101.011',from:2,to:10},[/5\.375/]);
  lb(19,{mode:'arithmetic',a:'3B7',b:'1F9',from:16,op:'subtract'},[/1BE/]);lb(20,{mode:'arithmetic',a:'11101',b:'101',from:2,op:'divide'},[/Resultado en base 2: 101;/,/residuo = 100/]);
  const logicParity=[];for(let x=1;x<=4;x++)for(let y=1;y<=4;y++)if((x+y)%2===0)logicParity.push(`${x},${y}`);
  ls(21,{mode:'relation',a:'1,2,3,4',pairs:logicParity.join('\n')},[/Reflexiva: sí; simétrica: sí; transitiva: sí/,/\{1, 3\}/,/\{2, 4\}/]);
  ls(22,{mode:'composition',slope:2,intercept:1,power:2},[/g∘f = \(\(2\)x\+\(1\)\)\^2/,/f∘g = \(2\)x\^2\+\(1\)/,/f⁻¹ = \(x−\(1\)\)\/\(2\)/]);
  ls(23,{mode:'cardinality',sizes:'30,25',intersections:'10',universe:60},[/Unión = 45; complemento = 15/]);
  lp(24,{expression:'((p→q)∧(q→r))→(p→r)'},[/tautology/,/8 asignaciones/]);
  lp(25,{mode:'argument',premises:'p→q\nq→r\n¬r',conclusion:'¬p'},[/Válido/]);
  lp(26,{mode:'induction',induction:'squares',n:10},[/Caso base/,/\(k\+1\)\(k\+2\)\(2k\+3\)\/6/,/385/]);
  lp(27,{mode:'induction',induction:'power2',n:5},[/2\(3m\+1\)/]);
  lk(28,{mode:'karnaugh',minterms:'1,3,5,7'},[/F = C\./,/G1/,/1, 3, 5, 7/,/Celdas/]);
  lk(29,{mode:'karnaugh'},[/AB/,/C/,/G2/]);lk(30,{mode:'karnaugh',source:'maxterms',minterms:'0,2,4'},[/AB/,/C/]);
  lg(31,{},[/estado euleriano: trail/,/no es euleriano cerrado/,/role="img"/]);
  for(const mode of ['bfs','dfs'])lg(32,{mode},[/Orden: \{A, B, C, D, E\}/,/role="img"/]);
  const logicWeightedEdges='A B 4\nA C 2\nB C 1\nB D 5\nC D 8\nC E 10\nD E 2';
  lg(33,{mode:'dijkstra',edges:logicWeightedEdges},[/Distancia mínima = 10/,/A → C → B → D → E/,/role="img"/]);
  const logicGuideTree={value:8,left:{value:3,left:{value:1},right:{value:6,left:{value:4},right:{value:7}}},right:{value:10,right:{value:14,left:{value:13}}}};
  lg(34,{mode:'classifytree',edges:'A B\nA C\nB D\nB E\nC F\nC G',start:'A'},[/altura 2 aristas/,/perfecto: sí/,/role="img"/]);
  lg(34,{mode:'tree',tree:JSON.stringify(logicGuideTree)},[/8, 3, 1, 6, 4, 7, 10, 14, 13/,/1, 3, 4, 6, 7, 8, 10, 13, 14/,/1, 4, 7, 6, 3, 13, 14, 10, 8/,/role="img"/]);
  lb(35,{mode:'twos',a:'-45'},[/11010011/]);lb(35,{mode:'add',a:'100',b:'-45'},[/00110111/,/Desbordamiento: no/]);
  lb(36,{mode:'bits',a:'B7',b:'5C',from:16},[/00010100/,/11111111/,/11101011/,/01001000/]);
  ls(37,{mode:'cardinality',sizes:'50,40,30',intersections:'15,10,12',triple:5,universe:''},[/Unión = 88/]);
  ls(38,{mode:'count',n:4,m:4},[/Relaciones binarias en A = 65536/,/reflexivas = 4096/,/simétricas = 1024/,/equivalencias = 15/]);
  ls(39,{mode:'count',n:4,m:7},[/inyectivas = 840/]);ls(39,{mode:'count',n:5,m:3},[/sobreyectivas = 150/]);
  lp(40,{mode:'proof'},[/supuesto se descarga/,/∨E, 3 y ramas 4–6, 7–9/]);
  for(const domain of ['Z','N'])ls(41,{mode:'integers','infinite-domain':domain},[/∀x∃y/,/∃y∀x/,/x\+y≠0/,/Testigo o contraejemplo/]);
  lp(42,{mode:'induction',induction:'power7',n:5},[/6\(7m\+1\)/]);lp(42,{mode:'induction',induction:'odds',n:5},[/\(k\+1\)²/]);
  lp(43,{mode:'induction',induction:'factorial',n:4},[/24 &gt; 16/,/k\+1≥5&gt;2/]);
  lk(44,{mode:'karnaugh',names:'A,B,C,D',minterms:'0,1,2,5,8,9,10'},[/-0-0/,/-00-/,/0-01/,/G3/]);
  lk(45,{mode:'karnaugh',names:'A,B,C,D',minterms:'1,3,7,11,15',dontcare:'0,2,5'},[/X \(m0\)/,/Celdas \(incluye X\)/]);
  lk(46,{mode:'nand',source:'formula',expression:'(A∨B)∧(¬A∨C)'},[/compuertas = 4/,/Σm = 2, 3, 5, 7/,/role="img"/]);
  lk(46,{mode:'nor',source:'formula',expression:'(A∨B)∧(¬A∨C)'},[/Realización NOR/,/role="img"/]);
  lg(47,{mode:'kruskal',edges:'A B 7\nA D 5\nB C 8\nB D 9\nB E 7\nC E 5\nD E 15\nD F 6\nE F 8\nE G 9\nF G 11'},[/peso total = 39/,/role="img"/]);
  lg(48,{mode:'flow',edges:'s a 10\ns b 5\na b 15\na t 5\nb t 10',start:'s',target:'t',directed:'directed'},[/Flujo máximo = 15/,/corte mínimo = 15/,/arcos inversos/,/role="img"/]);
  lg(49,{mode:'havel',sequence:'4,3,3,2,2'},[/La secuencia es gráfica/]);lg(49,{mode:'counts','count-left':3,'count-right':4},[/m·n<\/td><td>12/]);
  lg(50,{mode:'huffman',sequence:'a 45, b 13, c 12, d 16, e 9, f 5'},[/224/,/role="img"/]);
  assert.deepEqual([...logicCovered].sort((a,b)=>a-b),Array.from({length:50},(_,i)=>i+1));
  getElementById('logic-bool-source').value='minterms';
  getElementById('logic-bool-mode').value='minimal';
  actions.closeSubmod();
  actions.openSubmod('logic');
  for (const id of ['logic-bases','logic-sets','logic-propositions','logic-boolean','logic-graphs'])
    assert.match(getElementById('submod-cards').innerHTML,new RegExp(`data-arg="${id}"`));
  actions.launchSubmod('logic-bases');
  for (const [id,value] of Object.entries({'logic-base-mode':'convert','logic-base-a':'156','logic-base-b':'0','logic-base-from':'10','logic-base-to':'2','logic-base-width':'8'}))
    getElementById(id).value=value;
  actions.logicCalculateBases();
  assert.match(getElementById('logic-result').innerHTML,/10011100/);
  getElementById('logic-base-mode').value='arithmetic';
  getElementById('logic-base-op').value='multiply';
  getElementById('logic-base-a').value='1010';
  getElementById('logic-base-b').value='101';
  getElementById('logic-base-from').value='2';
  actions.logicCalculateBases();
  assert.match(getElementById('logic-result').innerHTML,/110010/);
  actions.closeModule('logic');
  actions.launchSubmod('logic-sets');
  for (const [id,value] of Object.entries({'logic-set-mode':'sets','logic-set-a':'1, 2, 3','logic-set-b':'3, 4'}))
    getElementById(id).value=value;
  actions.logicCalculateSets();
  assert.match(getElementById('logic-result').innerHTML,/A∩B = \{3\}/);
  getElementById('logic-set-mode').value='quantified';
  getElementById('logic-set-a').value='a, b';
  getElementById('logic-set-pairs').value='a,a\nb,b';
  getElementById('logic-set-outer').value='forall';
  getElementById('logic-set-inner').value='exists';
  actions.logicCalculateSets();
  assert.match(getElementById('logic-result').innerHTML,/∀x ∃y/);
  getElementById('logic-set-mode').value='integers';
  getElementById('logic-set-infinite-domain').value='N';
  actions.logicCalculateSets();
  assert.match(getElementById('logic-result').innerHTML,/ℕ=\{0,1,2,…\}/);
  assert.match(getElementById('logic-result').innerHTML,/∃x∀y/);
  actions.closeModule('logic');
  actions.launchSubmod('logic-propositions');
  getElementById('logic-prop-mode').value='table';
  getElementById('logic-prop-expression').value='(p→q)↔(¬p∨q)';
  actions.logicCalculateProposition();
  assert.match(getElementById('logic-result').innerHTML,/tautology/);
  getElementById('logic-prop-mode').value='forms';
  getElementById('logic-prop-expression').value='p→q';
  actions.logicCalculateProposition();
  assert.match(getElementById('logic-result').innerHTML,/FNC/);
  getElementById('logic-prop-mode').value='induction';
  getElementById('logic-prop-induction').value='factorial';
  getElementById('logic-prop-n').value='4';
  actions.logicCalculateProposition();
  assert.match(getElementById('logic-result').innerHTML,/4!=24/);
  assert.match(getElementById('logic-result').innerHTML,/k\+1≥5/);
  getElementById('logic-prop-mode').value='proof';
  actions.logicCalculateProposition();
  assert.match(getElementById('logic-result').innerHTML,/Prueba formal guiada/);
  assert.match(getElementById('logic-result').innerHTML,/ramas 4–6, 7–9/);
  actions.closeModule('logic');
  actions.launchSubmod('logic-boolean');
  getElementById('logic-bool-names').value='A, B, C';
  getElementById('logic-bool-minterms').value='1, 3, 5, 7';
  getElementById('logic-bool-dontcare').value='';
  actions.logicCalculateBoolean();
  assert.match(getElementById('logic-result').innerHTML,/F = C/);
  getElementById('logic-bool-mode').value='karnaugh';
  actions.logicCalculateBoolean();
  assert.match(getElementById('logic-result').innerHTML,/código Gray/);
  actions.closeModule('logic');
  actions.launchSubmod('logic-graphs');
  for (const [id,value] of Object.entries({'logic-graph-mode':'counts','logic-graph-count-edges':'7',
    'logic-graph-count-vertices':'6','logic-graph-count-left':'3','logic-graph-count-right':'4',
    'logic-graph-count-leaves':'8'})) getElementById(id).value=value;
  actions.logicCalculateGraph();
  assert.match(getElementById('logic-result').innerHTML,/Suma de grados con 7 aristas/);
  assert.match(getElementById('logic-result').innerHTML,/Aristas de K3,4/);
  assert.match(getElementById('logic-result').innerHTML,/binario lleno/);
  for (const [id,value] of Object.entries({'logic-graph-mode':'dijkstra','logic-graph-edges':'A B 4\nA C 2\nB C 1\nB D 5\nC D 8\nC E 10\nD E 2','logic-graph-start':'A','logic-graph-target':'E','logic-graph-directed':'undirected'}))
    getElementById(id).value=value;
  actions.logicCalculateGraph();
  assert.match(getElementById('logic-result').innerHTML,/Distancia mínima = 10/);
  assert.match(getElementById('logic-result').innerHTML,/Dijkstra: vértices fijados y camino mínimo/);
  assert.match(getElementById('logic-result').innerHTML,/<svg /);
  getElementById('logic-graph-mode').value='bfs';
  actions.logicCalculateGraph();
  assert.match(getElementById('logic-result').innerHTML,/Vértice visitado/);
  getElementById('logic-graph-mode').value='flow';
  getElementById('logic-graph-edges').value='s a 10\ns b 5\na b 15\na t 5\nb t 10';
  getElementById('logic-graph-start').value='s';
  getElementById('logic-graph-target').value='t';
  actions.logicCalculateGraph();
  assert.match(getElementById('logic-result').innerHTML,/Flujo máximo = 15/);
  assert.match(getElementById('logic-result').innerHTML,/Capacidad residual final/);
  assert.match(getElementById('logic-result').innerHTML,/Flujo máximo: lado alcanzable y corte mínimo/);
  getElementById('logic-graph-mode').value='matching';
  getElementById('logic-graph-left').value='A, B';
  getElementById('logic-graph-right').value='X, Y';
  getElementById('logic-graph-edges').value='A X\nB X\nB Y';
  actions.logicCalculateGraph();
  assert.match(getElementById('logic-result').innerHTML,/Tamaño máximo = 2/);
  assert.match(getElementById('logic-result').innerHTML,/Aristas resaltadas: parejas elegidas/);
  getElementById('logic-graph-mode').value='petri';
  getElementById('logic-graph-marking').value='1, 0';
  getElementById('logic-graph-transitions').value='[{"name":"mover","input":[1,0],"output":[0,1]}]';
  actions.logicCalculateGraph();
  assert.match(getElementById('logic-result').innerHTML,/Estados alcanzados: 2/);
  assert.match(getElementById('logic-result').innerHTML,/Red de alcanzabilidad de Petri/);
  getElementById('logic-graph-mode').value='tree';
  getElementById('logic-graph-tree').value='{"value":8,"left":{"value":3},"right":{"value":10}}';
  actions.logicCalculateGraph();
  assert.match(getElementById('logic-result').innerHTML,/Árbol binario/);
  getElementById('logic-graph-mode').value='huffman';
  getElementById('logic-graph-sequence').value='a 45, b 13, c 12, d 16, e 9, f 5';
  actions.logicCalculateGraph();
  assert.match(getElementById('logic-result').innerHTML,/Costo total = 224/);
  assert.match(getElementById('logic-result').innerHTML,/Árbol de Huffman/);
  actions.closeModule('logic');
  actions.closeSubmod();
});
