import test from 'node:test';
import assert from 'node:assert/strict';
import { createAppHarness } from './helpers/app-harness.mjs';

test('estadística, probabilidad y experimentos con historial', async () => {
  const harness = await createAppHarness();
  const { history, getElementById } = harness;
  const actions = harness.actions;
  const pi = Math.PI;
  // El recorrido original llegaba aquí desde el menú Matemáticas; el historial lo reproduce.
  actions.openSubmod('math');
  actions.openSubmod('math');

  assert.equal(getElementById('submod-screen').classList.contains('visible'), true);
  actions.closeSubmod();
  assert.equal(getElementById('submod-title').innerHTML.includes('Matemáticas'), true);
  actions.launchSubmod('stats');
  assert.equal(getElementById('stats-app').classList.contains('visible'), true);
  getElementById('stats-values').value = '2, 4, 4, 6, 9';
  actions.statsAnalyze();
  assert.match(getElementById('stats-result').innerHTML, /Mediana/);
  assert.match(getElementById('stats-result').innerHTML, /Varianza muestral/);
  assert.match(getElementById('stats-result').innerHTML, /Diagrama de caja/);
  actions.closeModule('stats');
  assert.equal(getElementById('submod-title').innerHTML.includes('Matemáticas'), true);
  history.forward();
  assert.equal(getElementById('stats-app').classList.contains('visible'), true);
  history.back();
  actions.openSubmod('prob');
  assert.match(getElementById('submod-back').innerHTML, /Matemáticas/);
  for (const id of ['prob-combinations','prob-coin','prob-dice'])
    assert.match(getElementById('submod-cards').innerHTML, new RegExp(`data-arg="${id}"`));
  actions.launchSubmod('prob-combinations');
  getElementById('prob-combinations-n').value = '10';
  getElementById('prob-combinations-k').value = '3';
  actions.probCalculateCombinations();
  assert.match(getElementById('prob-combinations-result').innerHTML, /120/);
  actions.closeModule('prob');
  actions.launchSubmod('prob-coin');
  assert.equal(getElementById('prob-app').classList.contains('visible'), true);
  assert.equal(getElementById('prob-coin-card').hidden, false);
  assert.equal(getElementById('prob-dice-card').hidden, true);
  getElementById('prob-coin-n').value = '4';
  getElementById('prob-coin-p').value = '0.5';
  getElementById('prob-coin-k').value = '2';
  actions.probCalculateCoin();
  assert.match(getElementById('prob-coin-result').innerHTML, /37\.5 %/);
  actions.closeModule('prob');
  assert.match(getElementById('submod-title').innerHTML, /Probabilidad/);
  actions.launchSubmod('prob-dice');
  assert.equal(getElementById('prob-dice-card').hidden, false);
  getElementById('prob-dice-n').value = '2';
  getElementById('prob-dice-sum').value = '7';
  actions.probCalculateDice();
  assert.match(getElementById('prob-dice-result').innerHTML, /Casos favorables/);
  actions.closeModule('prob');
  actions.closeSubmod();
  actions.openSubmod('exp');
  for (const id of ['exp-dice','exp-coin','exp-pi'])
    assert.match(getElementById('submod-cards').innerHTML, new RegExp(`data-arg="${id}"`));
  actions.launchSubmod('exp-pi');
  assert.equal(getElementById('exp-app').classList.contains('visible'), true);
  assert.equal(getElementById('exp-pi-card').hidden, false);
  getElementById('exp-pi-digits').value = '10';
  actions.expCalculatePi();
  assert.match(getElementById('exp-pi-result').innerHTML, /3\.1415926535/);
  actions.closeModule('exp');
  actions.launchSubmod('exp-dice');
  getElementById('exp-dice-count').value = '20';
  actions.expRollDice();
  assert.match(getElementById('exp-dice-result').innerHTML, /20 lanzamientos/);
  actions.closeModule('exp');
  actions.launchSubmod('exp-coin');
  getElementById('exp-coin-count').value = '20';
  actions.expFlipCoins();
  assert.match(getElementById('exp-coin-result').innerHTML, /Cara/);
  actions.closeModule('exp');
  actions.closeSubmod();
  actions.closeSubmod();
  assert.equal(getElementById('launcher').style.display, 'flex');
  history.forward();
  assert.equal(getElementById('submod-title').innerHTML.includes('Matemáticas'), true);
  assert.equal(getElementById('launcher').style.display, 'none');
  history.back();
});
